apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
  namespace: kyeol
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            # Inject sensitive values from Secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: saleor-dev-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: saleor-dev-secrets
                  key: SECRET_KEY
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: saleor-dev-secrets
                  key: RSA_PRIVATE_KEY
