apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
  namespace: kyeol
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            # Inject sensitive values from Secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: saleor-dev-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: saleor-dev-secrets
                  key: SECRET_KEY
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: saleor-dev-secrets
                  key: RSA_PRIVATE_KEY
            # Additional env vars for ALB proxy handling
            - name: SECURE_PROXY_SSL_HEADER
              value: HTTP_X_FORWARDED_PROTO,https
            - name: USE_X_FORWARDED_HOST
              value: "True"
            - name: ALLOWED_HOSTS
              value: '*'
