apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyeol

resources:
  - ../../base

images:
  - name: ghcr.io/saleor/saleor
    newTag: "3.22"

configMapGenerator:
  - name: saleor-api-env
    envs:
      - env-dev.properties

patchesStrategicMerge:
  - serviceaccount-patch.yaml
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml
