# Saleor Storefront - PROD Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyeol

resources:
  - ../../base
  - patches/hpa-patch.yaml

labels:
  - pairs:
      environment: prod
    includeSelectors: false

images:
  - name: ghcr.io/saleor/saleor
    newTag: "3.22"
  - name: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-storefront
    newName: 827913617839.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-prod-storefront
    newTag: prod-latest

patches:
  - target:
      kind: Deployment
      name: storefront
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: storefront
    path: patches/replicas-patch.yaml
  - target:
      kind: Ingress
      name: kyeol-ingress
    path: patches/ingress-patch.yaml
  - target:
      kind: Deployment
      name: storefront
    path: patches/resources-patch.yaml

  - target:
      kind: Deployment
      name: storefront
    path: patches/env-patch.yaml
