# Saleor Storefront - STAGE Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyeol

resources:
  - ../../base

labels:
  - pairs:
      environment: stage
    includeSelectors: false

images:
  - name: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-storefront
    newName: 827913617839.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-stage-storefront
    newTag: stage-latest

patches:
  - target:
      kind: Deployment
      name: storefront
    path: patches/replicas-patch.yaml
  - target:
      kind: Ingress
      name: kyeol-ingress
    path: patches/ingress-patch.yaml
  - target:
      kind: Deployment
      name: storefront
    path: patches/resources-patch.yaml
  - target:
      kind: Deployment
      name: storefront
    path: patches/env-patch.yaml

  # HPA Patch for STAGE
  - target:
      kind: HorizontalPodAutoscaler
      name: storefront-hpa
    path: patches/hpa-patch.yaml
