apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyeol

resources:
  - ../../base

images:
  - name: ghcr.io/saleor/saleor
    newTag: "3.22"

configMapGenerator:
  - name: saleor-api-env
    envs:
      - env-prod.properties

patchesStrategicMerge:
  - patches/serviceaccount-patch.yaml
  - patches/deployment-patch.yaml

patches:
  - target:
      kind: Ingress
      name: saleor-api
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.kyeol.click
  - target:
      kind: Deployment
      name: saleor-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - path: patches/ingress-patch.yaml
    target:
      kind: Ingress
      name: saleor-api
