# Saleor DEV Overlay: Kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyeol

resources:
  - ../../base

patches:
  - path: patches/ingress-patch.yaml
  - path: patches/replicas-patch.yaml

images:
  - name: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-storefront
    newName: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-storefront  # TODO: Replace with actual account ID
    newTag: dev-latest

commonLabels:
  environment: dev
