# Saleor DEV Overlay: Kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyeol

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: kyeol-ingress
    path: patches/ingress-patch.yaml
  - target:
      kind: Deployment
      name: storefront
    path: patches/replicas-patch.yaml
  - target:
      kind: Deployment
      name: storefront
    path: patches/env-patch.yaml

images:
  - name: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-storefront
    newName: 827913617839.dkr.ecr.ap-northeast-2.amazonaws.com/kyeol-dev-storefront
    newTag: dev-latest

commonLabels:
  environment: dev
